Fixando werkzeug==0.16.1
Apesar do Flask-OAuthlib se dizer compatível com werkzeug >= 0.14

```
Flask-OAuthlib==0.9.5
  - Flask [required: Any, installed: 1.0.2]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.11.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 1.0.0]

```

Isso não é verdade. Quando usandom `werkzeug==1.0.0` vemos essas
exceptions durante a rodada de testes:

```
   from flask_oauthlib.client import OAuth
../../../.local/share/virtualenvs/asgard-api-JX-ZQxSl/lib/python3.6/site-packages/flask_oauthlib/client.py:18: in <module>
    from werkzeug import url_quote, url_decode, url_encode
E   ImportError: cannot import name 'url_quote'
```